-- ============================================================
-- RestoPanel · Migration 0004 — Notifications for super admin
-- ============================================================
-- Real notification system for the super-admin bell.
-- Notifications are generated by:
--   - New tenant registration (event-driven, inserted by /api/auth/register)
--   - Tenant suspension / activation (inserted by /api/admin/tenants PATCH)
--   - High-severity audit events (impersonation, errors)
--   - System errors captured by API routes (optional)
--
-- Read/unread state is tracked per-user. Each notification has a type,
-- severity, target tenant (optional), title, message, and action URL.
-- ============================================================

create table if not exists notifications (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references users(id) on delete cascade,    -- recipient (super admin)
  type            text not null,                                  -- NEW_TENANT | TENANT_SUSPENDED | IMPERSONATION | ERROR | HIGH_CANCEL_RATE | RESERVATION_SPIKE
  severity        text not null default 'info',                   -- info | warning | error | success
  title           text not null,
  message         text not null,
  organization_id uuid references organizations(id) on delete set null,
  action_url      text,
  metadata        jsonb,
  read_at         timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists notifications_user_id_created_at_idx on notifications(user_id, created_at desc);
create index if not exists notifications_user_id_read_at_idx on notifications(user_id, read_at);

-- ============================================================
-- RLS for notifications
-- ============================================================
-- A user can only read/update their own notifications.
-- Inserts happen via the service_role key (server-side) so no INSERT
-- policy is needed for browser clients.
alter table notifications enable row level security;

drop policy if exists notifications_owner_select on notifications;
create policy notifications_owner_select on notifications
  for select using (user_id = auth.uid());

drop policy if exists notifications_owner_update on notifications;
create policy notifications_owner_update on notifications
  for update using (user_id = auth.uid());

-- ============================================================
-- Helper to create a notification for all super admins
-- ============================================================
-- We use a SECURITY DEFINER function so it can be called from a trigger
-- or from the API without worrying about RLS blocking the insert.
create or replace function notify_super_admins(
  p_type text,
  p_severity text,
  p_title text,
  p_message text,
  p_organization_id uuid default null,
  p_action_url text default null,
  p_metadata jsonb default null
)
returns void as $$
declare
  admin_record record;
begin
  for admin_record in
    select id from users where is_super_admin = true
  loop
    insert into notifications (
      user_id, type, severity, title, message,
      organization_id, action_url, metadata
    ) values (
      admin_record.id, p_type, p_severity, p_title, p_message,
      p_organization_id, p_action_url, p_metadata
    );
  end loop;
end;
$$ language plpgsql security definer;

comment on function notify_super_admins is
  'Creates a notification row for every super admin. Called from API routes when a relevant event happens (new tenant, suspension, high cancel rate, etc.).';
